services:
  frontend:
    image: ghcr.io/ripindensumite/thinwatcher-frontend:latest
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_API_URL=${VITE_BACKEND_API_URL}
  
  backend:
    image: ghcr.io/ripindensumite/thinwatcher-backend:latest
    ports:
      - "5000:3001"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=${PORT}
      - CORS_ORIGIN_PROD=${CORS_ORIGIN_PROD}
      - CORS_ORIGIN_DEV=${CORS_ORIGIN_DEV}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV}