name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Build frontend
        run: |
          cd app
          npm ci
          npm run build
          
      - name: Copy dist to backend
        run: |
          mkdir -p backend/dist
          cp -r app/dist/* backend/dist/
      
      - name: Convert username to lowercase
        id: lowercase_username
        uses: Entepotenz/change-string-case-action-min-dependencies@v1
        with:
          string: ${{ github.actor }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push combined image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ steps.lowercase_username.outputs.lowercase }}/thinwatcher:latest