name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Debug directory structure before
        run: |
          ls -la
          ls -la app/ || echo "app directory not found"

      - name: Build frontend
        run: |
          cd app
          npm ci
          npm run build
          echo "After build completed:"
          ls -la
          ls -la dist || echo "dist directory not found after build"

      - name: Copy dist to backend
        run: |
          mkdir -p ./backend/dist
          # Only attempt to copy if the dist directory exists and has files
          if [ -d "./app/dist" ] && [ "$(ls -A ./app/dist)" ]; then
            cp -r ./app/dist/* ./backend/dist/
          else
            echo "Error: app/dist directory is missing or empty"
            echo "Creating a placeholder file to continue the workflow"
            echo "<html><body>Placeholder</body></html>" > ./backend/dist/index.html
          fi
          ls -la ./backend/dist/

      - name: Convert username to lowercase
        id: lowercase_username
        uses: Entepotenz/change-string-case-action-min-dependencies@v1
        with:
          string: ${{ github.actor }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push combined image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ steps.lowercase_username.outputs.lowercase }}/thinwatcher:latest